nginx:
  image: nginx
  ports:
    - "8080:80"
  volumes:
    # override the default site
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - ./html:/etc/nginx/html:ro
  links:
    - fpm

fpm:
  image: 'php:5-fpm'
  volumes:
    - ./html:/var/www/html

